name: ğŸš€ Test & Deploy Static Content to GitHub Pages

on: push

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read # Read access to repository contents
  pages: write # Write access for deployment to GitHub Pages
  id-token: write # Allow GitHub to issue an ID token for authentication

# Allow only one concurrent deployment at a time
concurrency:
  group: pages # Group deployments by name for concurrency control
  cancel-in-progress: true # Cancel any in-progress deployments if a new one starts

jobs:
  # Setup environment and dependencies
  setup:
    name: ğŸ› ï¸ Setup Development Environment
    runs-on: ubuntu-latest
    outputs:
      node-modules-path: ${{ steps.cache-dependencies.outputs.cache-hit }}

    steps:
      - name: Checkout Repository ğŸ“¥
        uses: actions/checkout@v4

      - name: Cache Dependencies ğŸ“¦
        uses: actions/cache@v4
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js Environment âš™ï¸
        uses: ./.github/actions/setup
        with:
          node-version: 20

      - name: Install Dependencies ğŸ› ï¸
        run: yarn install --immutable
        if: steps.cache-dependencies.outputs.cache-hit != 'true' # Only install if cache miss

      - name: Run Linter ğŸ§‘â€ğŸ’»
        run: yarn lint

  tests:
    name: ğŸ” Execute Unit Tests
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository ğŸ“¥
        uses: actions/checkout@v4

      - name: Setup Node.js Environment âš™ï¸
        uses: ./.github/actions/setup
        with:
          node-version: 20

      - name: Install Dependencies ğŸ› ï¸
        run: yarn install --immutable

      - name: Run Tests ğŸ§ª
        run: yarn test

  deploy:
    name: ğŸš€ Deploy to GitHub Pages
    needs: [setup, tests]
    if: github.ref == 'refs/heads/main' # Only deploy from the main branch

    environment:
      name: github-pages # Set deployment environment to GitHub Pages
      url: ${{ steps.deployment.outputs.page_url }} # Output page URL

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository ğŸ“¥
        uses: actions/checkout@v4

      - name: Setup Node.js Environment âš™ï¸
        uses: ./.github/actions/setup
        with:
          node-version: 20

      - name: Install Dependencies ğŸ› ï¸
        run: yarn install --immutable

      - name: Build Static Content ğŸ—ï¸
        run: yarn build:demo # Build the static site with Vite

      - name: Setup GitHub Pages âš™ï¸
        uses: actions/configure-pages@v4

      - name: Upload Build Artifacts ğŸ“¦
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./demo # Path to the build output directory

      - name: Deploy to GitHub Pages ğŸŒ
        id: deployment
        uses: actions/deploy-pages@v4 # Deploy the build to GitHub Pages
